export const ERRORS = {
  USER_CREATION: "USER_CREATION",
  USER_SEARCH: "USER_SEARCH",
  PAYLOAD_PARSING: "PAYLOAD_PARSING",
  USER_VERIFICATION: "USER_VERIFICATION",
  DB_ERROR: "DB_ERROR",
  TRANSACTION_ERROR: "TRANSACTION_ERROR",
  ROUTES_MIDDLEWARE_ERROR: "ROUTES_MIDDLEWARE_ERROR"
} as const;

export type MyServerError = {
  type: keyof typeof ERRORS;
  message: string;
};

